### ISSUE TITLE
pypi integration?

### ISSUE THREAD

**Issue by willzfarmer** [imh/hipsterplot#6]
Can we get this up on pypi so we can install just with `pip install hipsterplot`? I use it a lot and I would love a better installation method...

**Comment by danilobellini** [comment]
I've already prepared the project to that some time ago. For now you can do:

```
pip install git+https://github.com/imh/hipsterplot
```

To allow `pip install hipsterplot` someone just needs to register the project on PyPI. I can do that if Ian Horn allows me.

**Comment by imh** [comment]
Go ahead!

**Comment by danilobellini** [comment]
PyPI classifiers were modified, so the code needs a small change. It just needs replacing (twice) the "Software Development" by "Scientific/Engineering". That should be enough, but you can also insert a new `"Programming Language :: Python :: 3.5"` classifier. It's really a simple and bureaucratic change, but I can make a pull request for that if you wish. Afterwards, a `git tag v0.1` with a `git push --tags` would be useful (and AFAIK tags are never part of a pull request). If you add me as a collaborator in the GitHub project settings, I can do all these steps directly. Else I'll wait the changes to upload to PyPI a version of the code that is actually stored here (not only in my fork).

**Comment by imh** [comment]
You seem to know what you're doing with this better than I do, so I added you as a collaborator. Thanks for all the help on this.

**Comment by danilobellini** [comment]
Done. To rebuild the 3 files I've pushed to PyPI:
```
python setup.py sdist --formats gztar,zip bdist_wheel --universal
```
I think there's no need for other distribution formats.

**Comment by danilobellini** [comment]
An extra that might be useful for some, I've added this to AUR:

https://aur.archlinux.org/packages/python-hipsterplot/
https://aur.archlinux.org/packages/python2-hipsterplot/

**Comment by imh** [comment]
Thanks again :)
